version: '3'

services:
  trojan:
      image: jeonkwan/trojan
      restart: always
      ports:
        - "443:443"
      volumes:
        - ./trojan/config:/config
        - ./ssl:/ssl
        - ./trojan/wait_for_caddy.sh:/wait_for_caddy.sh
      links:
        - caddy:__DOCKER_CADDY__
      depends_on: 
        - caddy

  caddy:
      image: abiosoft/caddy
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./wwwroot:/usr/src
        - ./caddy/Caddyfile:/etc/Caddyfile
        - ./ssl:/root/.caddy/acme/acme-v02.api.letsencrypt.org/sites